#lang info

;; Spacemacs Themes for DrRacket
;; pkg metadata
(define deps '("base"))

;; Spacemacs Common Colors
(define green                    #(103 177 29))
(define magenta                  #(163 29 177))
(define red                      #(242 36 31))
(define yellow                   #(177 149 29))

(define comment                  #(42 161 174))
(define error                    #(224 33 29))
(define warning                  #(220 117 47))
(define string                   #(45 149 116))

;; Spacemacs Light Colors
(define light-blue               #(58 129 195))
(define light-cyan               #(33 184 199))
(define light-green              green)
(define light-magenta            magenta)
(define light-red                red)
(define light-yellow             yellow)

(define light-background         #(251 248 239))
(define light-comment            comment)
(define light-constant           #(78 49 99))
(define light-error              error)
(define light-foreground         #(101 83 112))
(define light-dim                #(160 148 162))
(define light-function           #(108 49 99))
(define light-highlight          #(211 211 231 0.5))
(define light-highlight-dim      #(231 231 251 0.5))
(define light-isearch-background #(186 47 89 0.75))
(define light-keyword            light-blue)
(define light-paren-match        #(210 206 218 0.5))
(define light-string             string)
(define light-variable           #(113 90 177))
(define light-warning            warning)
(define light-output             #(108 65 115))

;; Spacemacs Dark Colors
(define dark-blue                #(79 151 215))
(define dark-cyan                #(40 222 240))
(define dark-green               green)
(define dark-magenta             magenta)
(define dark-red                 red)
(define dark-yellow              yellow)

(define dark-background          #(41 43 46))
(define dark-comment             comment)
(define dark-constant            #(164 91 173))
(define dark-error               error)
(define dark-foreground          #(178 178 178))
(define dark-dim                 #(104 104 104))
(define dark-function            #(188 110 197))
(define dark-highlight           #(68 65 85 0.5))
(define dark-highlight-dim       #(48 45 65 0.5))
(define dark-isearch-background  #(134 220 47 0.85))
(define dark-keyword             dark-blue)
(define dark-paren-match         #(41 66 45 0.5))
(define dark-string              string)
(define dark-variable            #(117 144 219))
(define dark-warning             warning)
(define dark-output              #(197 110 195))

(define framework:color-schemes
  `(#hash((name . "Spacemacs Light")
          (white-on-black-base? . #f)
          (colors
           .
           (
            (drracket:check-syntax:both-obligation-style-pref       ,light-yellow)
            (drracket:check-syntax:free-variable                    ,light-red)
            (drracket:check-syntax:imported                         ,light-magenta)
            (drracket:check-syntax:lexically-bound                  ,light-keyword)
            (drracket:check-syntax:my-obligation-style-pref         ,light-cyan)
            (drracket:check-syntax:set!d                            ,light-warning)
            (drracket:check-syntax:their-obligation-style-pref      ,light-green)
            (drracket:check-syntax:unk-obligation-style-pref        ,light-warning)
            (drracket:check-syntax:unused-require                   ,light-red)
            (drracket:read-eval-print-loop:error-color              ,light-error)
            (drracket:read-eval-print-loop:out-color                ,light-output)
            (drracket:read-eval-print-loop:value-color              ,light-keyword)
            (drracket:syncheck:matching-identifiers                 ,dark-isearch-background)
            (framework:basic-canvas-background                      ,light-background)
            (framework:default-text-color                           ,light-foreground)
            (framework:misspelled-text-color                        ,light-warning)
            (framework:paren-match-color                            ,light-highlight)
            (framework:syntax-color:scheme:comment                  ,light-comment)
            (framework:syntax-color:scheme:constant                 ,light-constant)
            (framework:syntax-color:scheme:error                    ,light-error)
            (framework:syntax-color:scheme:hash-colon-keyword       ,light-keyword bold)
            (framework:syntax-color:scheme:keyword                  ,light-keyword)
            (framework:syntax-color:scheme:other                    ,light-foreground)
            (framework:syntax-color:scheme:parenthesis              ,light-dim)
            (framework:syntax-color:scheme:string                   ,light-string)
            (framework:syntax-color:scheme:symbol                   ,light-foreground)
            (framework:syntax-color:scheme:text                     ,light-comment)
            ;; (plt:htdp:test-coverage-off                          ,light-warning bold)
            (plt:htdp:test-coverage-on                              ,light-foreground)
            ;; (plt:module-language:test-coverage-off               ,light-warning bold)
            (plt:module-language:test-coverage-on                   ,light-foreground))))

    #hash((name . "Spacemacs Dark")
          (white-on-black-base? . #t)
          (colors
           .
           ((drracket:check-syntax:both-obligation-style-pref       ,dark-yellow)
            (drracket:check-syntax:free-variable                    ,dark-red)
            (drracket:check-syntax:imported                         ,dark-magenta)
            (drracket:check-syntax:lexically-bound                  ,dark-keyword)
            (drracket:check-syntax:my-obligation-style-pref         ,dark-cyan)
            (drracket:check-syntax:set!d                            ,dark-warning)
            (drracket:check-syntax:their-obligation-style-pref      ,dark-green)
            (drracket:check-syntax:unk-obligation-style-pref        ,dark-warning)
            (drracket:check-syntax:unused-require                   ,dark-red)
            (drracket:read-eval-print-loop:error-color              ,dark-error)
            (drracket:read-eval-print-loop:out-color                ,dark-output)
            (drracket:read-eval-print-loop:value-color              ,dark-keyword)
            (drracket:syncheck:matching-identifiers                 ,light-isearch-background)
            (framework:basic-canvas-background                      ,dark-background)
            (framework:default-text-color                           ,dark-foreground)
            (framework:misspelled-text-color                        ,dark-warning)
            (framework:paren-match-color                            ,dark-highlight)
            (framework:syntax-color:scheme:comment                  ,dark-comment)
            (framework:syntax-color:scheme:constant                 ,dark-constant)
            (framework:syntax-color:scheme:error                    ,dark-error)
            (framework:syntax-color:scheme:hash-colon-keyword       ,dark-keyword bold)
            (framework:syntax-color:scheme:keyword                  ,dark-keyword)
            (framework:syntax-color:scheme:other                    ,dark-foreground)
            (framework:syntax-color:scheme:parenthesis              ,dark-dim)
            (framework:syntax-color:scheme:string                   ,dark-string)
            (framework:syntax-color:scheme:symbol                   ,dark-foreground)
            (framework:syntax-color:scheme:text                     ,dark-comment)
            ;; (plt:htdp:test-coverage-off                          ,dark-warning bold)
            (plt:htdp:test-coverage-on                              ,dark-foreground)
            ;; (plt:module-language:test-coverage-off               ,dark-warning bold)
            (plt:module-language:test-coverage-on                   ,dark-foreground))))))
